# Generated by Django 4.0.4 on 2022-05-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocation',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
